server:
  contextPath: /ft

logging:
  level:
    romanusyk.ft: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

spring:
  profiles:
    active: "dev"

ft:
  token:
    header: "X-Auth-Token"

---


spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/ft
    driver-class-name: org.postgresql.Driver
    username: romm
    password: romm
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgresPlusDialect


---


spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect